### ISSUE TITLE
Unsigncuts doesn’t work on Dopamine

### ISSUE THREAD

**Issue by Dr-Sauce** [0xilis/Unsigncuts#1]
![6DE02376-17AE-4196-B863-22D1E7E372E9](https://github.com/0xilis/Unsigncuts/assets/82555878/b0920c94-8b14-4b04-934b-03fa26549eaa)

**Comment by luhgarlicbread** [comment]
Yuh same

**Comment by Dr-Sauce** [comment]
@luhgarlicbread I found a fix. Toggle options in unsigncuts settings.
